Review request for private event project
chrystalme/private-events pull request #3
Opened 2021-03-05 17:04 UTC by chrystalme

## Private Event project
- A project for users to create invent that can be viewed by everyone but only signed-in users can attend.
- The project shows how associations work in rails. 
   - Belongs_to
   - has_many
   - has_many through
- scope 
- class_name

2021-03-05 21:14 UTC, GzimAsani requested changes
### Status: Changes Required :recycle: 

### Hello team, good job so far, but you have to do the following changes:
- [x] Your picture in readme file is broken, kindly fix that
- [ ] I cannot create new events I get the following error also delete this line `Events#new
Find me in app/views/events/new.html.erb`  ![Screenshot from 2021-03-05 21-49-04](https://user-images.githubusercontent.com/62705947/110173565-135e1f00-7dff-11eb-9090-5a677d1c4f1a.png)
- [x] Event model should belong to creator/user ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_assoc_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))

#### Controllers

##### EventsController

- [x] `index` action should: 
-  lists past events, i.e. `@past_events = Event.previous_events` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/past_upcoming_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
- lists ucomping events, i.e. `@upcoming_events = Event.upcoming_events` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/past_upcoming_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))

### Please implement these changes and ask for another code review whenever you are ready

_**If you have any question related to the required changes feel free to text me on chat @GzimAsani**_

HAPPY CODING :computer: :desktop_computer:

2021-03-06 14:09 UTC, mke2111 requested changes
# **STATUS: CHANGES REQUIRED 🔴 ⚠️** 

## Hey @chrystalme & @ahmetbozaci, 👋🏽 
 **Thank you for the good job you got going on and making the requested changes**

## REQUIRED CHANGES

- [x] Add the linter files to your project. This will enable the github check to be done. You have 6 rubocop offenses locally.
- [ ] The event's show page should display a list of attendants of each event. As of now, all events belong to the signed-in user, even if they did not create the event, and have not opted to attend. You can choose to use a button that adds attendants of the event.
- [x] The index action of events controller should list both the past and upcoming events. Make the changes as requested in the previous review.

**Kindly make all the requested changes and submit another CRR. 👍🏽** 

## Cheers!! 🍹 & Happy Coding.

# Reach me on slack for a chitchat 🆘  **Roy Mukuye**

2021-03-07 00:16 UTC, MahmoudBakr23 requested changes
# **Changes Required 🛑♻**

<hr>

Hello there, I must admit, great job working on this project so far and on the requested changes, it looks perfect. However, there are still a few more issues to make before moving on. :)

- [ ] Please consider making the upcoming and past events defined in the action index within the events controller. (As requested by previous reviewers)
- [ ] Kindly remove any related logic from your views and place it in the helpers as methods.

<hr>

Kindly make the required changes and ask for another CRR. :)
Good luck, happy coding, and keep up this great work. :)

2021-03-08 04:39 UTC, umairarshadbutt requested changes
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @chrystalme and @ahmetbozaci 
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed.

##

Kindly work on the suggested changes  👇.
- [x] Kindly remove any related logic from your views and place it in the helpers as methods.
##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

2021-03-08 15:23 UTC, ahmetbozaci commented
We move logic code from view as we can like everyone. 
We create method in helpers and we use partial in view.
I looked all TSE's project for how we do it. Everyone has logic in view.
TSE 's doesnt look code. Please check code.

2021-03-08 18:11 UTC, acushlakoncept requested changes
# Status: Changes Required ♻️

Hello @ahmetbozaci and @chrystalme, Great job! 👏  Both of you have done well on this project. Your UI looks good 👏👏👏

However, there are still some changes that are necessary for this project to be approved.
Let us quickly add some finishing touches and request another review.

- [x] I noticed there are lots of logic in your views, there should be absolutely NO logic in views. Views are only for displaying information that became available to it from its corresponding controller not generating it.  ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from Pathwright)
I have gone ahead and made some comments on your codebase see affected files below:

**Don't know where to start or how to?** See  [Rails View Helpers Best Practices](https://medium.com/@acushla4real/rails-view-helpers-best-practices-guide-d7d7b6db3db4) 

#### Tests

* [x] Your models should have unit tests for validations and associations (Rspec) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/unit_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/))
* [x] Your authentication should have has integration tests (Rspec + Capybara) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/integration_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/))
* [x] Your event managment features should have integration tests (Rspec + Capybara) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/integration_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/))


### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla) or reply to this thread, if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

2021-03-08 18:11 UTC, acushlakoncept commented on app/views/events/_form.html.erb
> +  <% end %>
there should be absolutely NO logic in views.

2021-03-08 18:11 UTC, acushlakoncept commented on app/views/events/_show_events.html.erb
> +  <% end %>
there should be absolutely NO logic in views.

2021-03-08 18:11 UTC, acushlakoncept commented on app/views/layouts/application.html.erb
> +        <% end %>
there should be absolutely NO logic in views.

2021-03-08 18:11 UTC, acushlakoncept commented on app/views/shared/_flash.html.erb
> +<% end %>
there should be absolutely NO logic in views.

2021-03-08 18:11 UTC, acushlakoncept commented on app/views/users/_form.html.erb
> +  <div class="field">
there should be absolutely NO logic in views.

2021-03-08 18:11 UTC, acushlakoncept commented on app/views/users/_show.html.erb
> +<% end %>
there should be absolutely NO logic in views.

2021-03-11 16:21 UTC, MahmoudBakr23 approved these changes
# **Approved ✔✔**

<hr>

Hello Team :)
Good work you've done on this app and on the requested changes.
Thank you for the huge efforts :)
You may now merge and submit.
Good luck with the next and always happy coding 👨‍💻💻😊

2021-03-11 16:28 UTC, merged